// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package spotify.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;

public class SearchJava extends CustomJavaAction<String>
{
	private String SearchString;
	private spotify.proxies.SearchType SearchTypeParameter1;

	public SearchJava(IContext context, String SearchString, String SearchTypeParameter1)
	{
		super(context);
		this.SearchString = SearchString;
		this.SearchTypeParameter1 = SearchTypeParameter1 == null ? null : spotify.proxies.SearchType.valueOf(SearchTypeParameter1);
	}

	@Override
	public String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return search(SearchString.replaceAll(" ", "%20"), SearchTypeParameter1.getCaption());
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "SearchJava";
	}

	// BEGIN EXTRA CODE
	private String search(String searchString, String searchType){
        return webRequest("https://api.spotify.com/v1/search?q=" + searchString + "&type=" + searchType);
    }

    private String webRequest(String url){
        String response = "";
        try {
            URLConnection connection = new URL(url).openConnection();
            BufferedReader br = new BufferedReader(new InputStreamReader((connection.getInputStream())));
            StringBuilder sb = new StringBuilder();
            String output;
            while ((output = br.readLine()) != null) {
                sb.append(output);
            }
            response = sb.toString();
        } catch (Exception e){}
        return response;
    }
	// END EXTRA CODE
}
