// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package spotify.proxies;

public class Available_markets
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject available_marketsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Spotify.Available_markets";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Available_markets_JsonObject("Spotify.Available_markets_JsonObject"),
		Available_markets_Album("Spotify.Available_markets_Album");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Available_markets(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Spotify.Available_markets"));
	}

	protected Available_markets(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject available_marketsMendixObject)
	{
		if (available_marketsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Spotify.Available_markets", available_marketsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Spotify.Available_markets");

		this.available_marketsMendixObject = available_marketsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Available_markets.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static spotify.proxies.Available_markets initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return spotify.proxies.Available_markets.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static spotify.proxies.Available_markets initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new spotify.proxies.Available_markets(context, mendixObject);
	}

	public static spotify.proxies.Available_markets load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return spotify.proxies.Available_markets.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Available_markets_JsonObject
	 */
	public final spotify.proxies.JsonObject getAvailable_markets_JsonObject() throws com.mendix.core.CoreException
	{
		return getAvailable_markets_JsonObject(getContext());
	}

	/**
	 * @param context
	 * @return value of Available_markets_JsonObject
	 */
	public final spotify.proxies.JsonObject getAvailable_markets_JsonObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		spotify.proxies.JsonObject result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Available_markets_JsonObject.toString());
		if (identifier != null)
			result = spotify.proxies.JsonObject.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Available_markets_JsonObject
	 * @param available_markets_jsonobject
	 */
	public final void setAvailable_markets_JsonObject(spotify.proxies.JsonObject available_markets_jsonobject)
	{
		setAvailable_markets_JsonObject(getContext(), available_markets_jsonobject);
	}

	/**
	 * Set value of Available_markets_JsonObject
	 * @param context
	 * @param available_markets_jsonobject
	 */
	public final void setAvailable_markets_JsonObject(com.mendix.systemwideinterfaces.core.IContext context, spotify.proxies.JsonObject available_markets_jsonobject)
	{
		if (available_markets_jsonobject == null)
			getMendixObject().setValue(context, MemberNames.Available_markets_JsonObject.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Available_markets_JsonObject.toString(), available_markets_jsonobject.getMendixObject().getId());
	}

	/**
	 * @return value of Available_markets_Album
	 */
	public final spotify.proxies.Album getAvailable_markets_Album() throws com.mendix.core.CoreException
	{
		return getAvailable_markets_Album(getContext());
	}

	/**
	 * @param context
	 * @return value of Available_markets_Album
	 */
	public final spotify.proxies.Album getAvailable_markets_Album(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		spotify.proxies.Album result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Available_markets_Album.toString());
		if (identifier != null)
			result = spotify.proxies.Album.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Available_markets_Album
	 * @param available_markets_album
	 */
	public final void setAvailable_markets_Album(spotify.proxies.Album available_markets_album)
	{
		setAvailable_markets_Album(getContext(), available_markets_album);
	}

	/**
	 * Set value of Available_markets_Album
	 * @param context
	 * @param available_markets_album
	 */
	public final void setAvailable_markets_Album(com.mendix.systemwideinterfaces.core.IContext context, spotify.proxies.Album available_markets_album)
	{
		if (available_markets_album == null)
			getMendixObject().setValue(context, MemberNames.Available_markets_Album.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Available_markets_Album.toString(), available_markets_album.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return available_marketsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final spotify.proxies.Available_markets that = (spotify.proxies.Available_markets) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Spotify.Available_markets";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
