// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package spotify.proxies;

public class External_urls_2
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject external_urls_2MendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Spotify.External_urls_2";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Spotify("Spotify"),
		External_urls_2_JsonObject_2("Spotify.External_urls_2_JsonObject_2"),
		External_urls_2__owner("Spotify.External_urls_2__owner");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public External_urls_2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Spotify.External_urls_2"));
	}

	protected External_urls_2(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject external_urls_2MendixObject)
	{
		if (external_urls_2MendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Spotify.External_urls_2", external_urls_2MendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Spotify.External_urls_2");

		this.external_urls_2MendixObject = external_urls_2MendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'External_urls_2.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static spotify.proxies.External_urls_2 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return spotify.proxies.External_urls_2.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static spotify.proxies.External_urls_2 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new spotify.proxies.External_urls_2(context, mendixObject);
	}

	public static spotify.proxies.External_urls_2 load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return spotify.proxies.External_urls_2.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Spotify
	 */
	public final String getSpotify()
	{
		return getSpotify(getContext());
	}

	/**
	 * @param context
	 * @return value of Spotify
	 */
	public final String getSpotify(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Spotify.toString());
	}

	/**
	 * Set value of Spotify
	 * @param spotify
	 */
	public final void setSpotify(String spotify)
	{
		setSpotify(getContext(), spotify);
	}

	/**
	 * Set value of Spotify
	 * @param context
	 * @param spotify
	 */
	public final void setSpotify(com.mendix.systemwideinterfaces.core.IContext context, String spotify)
	{
		getMendixObject().setValue(context, MemberNames.Spotify.toString(), spotify);
	}

	/**
	 * @return value of External_urls_2_JsonObject_2
	 */
	public final spotify.proxies.JsonObject_2 getExternal_urls_2_JsonObject_2() throws com.mendix.core.CoreException
	{
		return getExternal_urls_2_JsonObject_2(getContext());
	}

	/**
	 * @param context
	 * @return value of External_urls_2_JsonObject_2
	 */
	public final spotify.proxies.JsonObject_2 getExternal_urls_2_JsonObject_2(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		spotify.proxies.JsonObject_2 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.External_urls_2_JsonObject_2.toString());
		if (identifier != null)
			result = spotify.proxies.JsonObject_2.load(context, identifier);
		return result;
	}

	/**
	 * Set value of External_urls_2_JsonObject_2
	 * @param external_urls_2_jsonobject_2
	 */
	public final void setExternal_urls_2_JsonObject_2(spotify.proxies.JsonObject_2 external_urls_2_jsonobject_2)
	{
		setExternal_urls_2_JsonObject_2(getContext(), external_urls_2_jsonobject_2);
	}

	/**
	 * Set value of External_urls_2_JsonObject_2
	 * @param context
	 * @param external_urls_2_jsonobject_2
	 */
	public final void setExternal_urls_2_JsonObject_2(com.mendix.systemwideinterfaces.core.IContext context, spotify.proxies.JsonObject_2 external_urls_2_jsonobject_2)
	{
		if (external_urls_2_jsonobject_2 == null)
			getMendixObject().setValue(context, MemberNames.External_urls_2_JsonObject_2.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.External_urls_2_JsonObject_2.toString(), external_urls_2_jsonobject_2.getMendixObject().getId());
	}

	/**
	 * @return value of External_urls_2__owner
	 */
	public final spotify.proxies._owner getExternal_urls_2__owner() throws com.mendix.core.CoreException
	{
		return getExternal_urls_2__owner(getContext());
	}

	/**
	 * @param context
	 * @return value of External_urls_2__owner
	 */
	public final spotify.proxies._owner getExternal_urls_2__owner(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		spotify.proxies._owner result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.External_urls_2__owner.toString());
		if (identifier != null)
			result = spotify.proxies._owner.load(context, identifier);
		return result;
	}

	/**
	 * Set value of External_urls_2__owner
	 * @param external_urls_2__owner
	 */
	public final void setExternal_urls_2__owner(spotify.proxies._owner external_urls_2__owner)
	{
		setExternal_urls_2__owner(getContext(), external_urls_2__owner);
	}

	/**
	 * Set value of External_urls_2__owner
	 * @param context
	 * @param external_urls_2__owner
	 */
	public final void setExternal_urls_2__owner(com.mendix.systemwideinterfaces.core.IContext context, spotify.proxies._owner external_urls_2__owner)
	{
		if (external_urls_2__owner == null)
			getMendixObject().setValue(context, MemberNames.External_urls_2__owner.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.External_urls_2__owner.toString(), external_urls_2__owner.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return external_urls_2MendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final spotify.proxies.External_urls_2 that = (spotify.proxies.External_urls_2) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Spotify.External_urls_2";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
