// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package spotify.proxies;

public class External_urls_3
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject external_urls_3MendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Spotify.External_urls_3";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Spotify("Spotify"),
		External_urls_3_Root("Spotify.External_urls_3_Root");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public External_urls_3(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Spotify.External_urls_3"));
	}

	protected External_urls_3(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject external_urls_3MendixObject)
	{
		if (external_urls_3MendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Spotify.External_urls_3", external_urls_3MendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Spotify.External_urls_3");

		this.external_urls_3MendixObject = external_urls_3MendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'External_urls_3.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static spotify.proxies.External_urls_3 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return spotify.proxies.External_urls_3.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static spotify.proxies.External_urls_3 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new spotify.proxies.External_urls_3(context, mendixObject);
	}

	public static spotify.proxies.External_urls_3 load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return spotify.proxies.External_urls_3.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Spotify
	 */
	public final String getSpotify()
	{
		return getSpotify(getContext());
	}

	/**
	 * @param context
	 * @return value of Spotify
	 */
	public final String getSpotify(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Spotify.toString());
	}

	/**
	 * Set value of Spotify
	 * @param spotify
	 */
	public final void setSpotify(String spotify)
	{
		setSpotify(getContext(), spotify);
	}

	/**
	 * Set value of Spotify
	 * @param context
	 * @param spotify
	 */
	public final void setSpotify(com.mendix.systemwideinterfaces.core.IContext context, String spotify)
	{
		getMendixObject().setValue(context, MemberNames.Spotify.toString(), spotify);
	}

	/**
	 * @return value of External_urls_3_Root
	 */
	public final spotify.proxies.Root getExternal_urls_3_Root() throws com.mendix.core.CoreException
	{
		return getExternal_urls_3_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of External_urls_3_Root
	 */
	public final spotify.proxies.Root getExternal_urls_3_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		spotify.proxies.Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.External_urls_3_Root.toString());
		if (identifier != null)
			result = spotify.proxies.Root.load(context, identifier);
		return result;
	}

	/**
	 * Set value of External_urls_3_Root
	 * @param external_urls_3_root
	 */
	public final void setExternal_urls_3_Root(spotify.proxies.Root external_urls_3_root)
	{
		setExternal_urls_3_Root(getContext(), external_urls_3_root);
	}

	/**
	 * Set value of External_urls_3_Root
	 * @param context
	 * @param external_urls_3_root
	 */
	public final void setExternal_urls_3_Root(com.mendix.systemwideinterfaces.core.IContext context, spotify.proxies.Root external_urls_3_root)
	{
		if (external_urls_3_root == null)
			getMendixObject().setValue(context, MemberNames.External_urls_3_Root.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.External_urls_3_Root.toString(), external_urls_3_root.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return external_urls_3MendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final spotify.proxies.External_urls_3 that = (spotify.proxies.External_urls_3) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Spotify.External_urls_3";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
