// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package spotify.proxies;

public class External_urls
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject external_urlsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Spotify.External_urls";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Spotify("Spotify"),
		External_urls_JsonObject("Spotify.External_urls_JsonObject"),
		External_urls_Album("Spotify.External_urls_Album");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public External_urls(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Spotify.External_urls"));
	}

	protected External_urls(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject external_urlsMendixObject)
	{
		if (external_urlsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Spotify.External_urls", external_urlsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Spotify.External_urls");

		this.external_urlsMendixObject = external_urlsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'External_urls.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static spotify.proxies.External_urls initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return spotify.proxies.External_urls.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static spotify.proxies.External_urls initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new spotify.proxies.External_urls(context, mendixObject);
	}

	public static spotify.proxies.External_urls load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return spotify.proxies.External_urls.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Spotify
	 */
	public final String getSpotify()
	{
		return getSpotify(getContext());
	}

	/**
	 * @param context
	 * @return value of Spotify
	 */
	public final String getSpotify(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Spotify.toString());
	}

	/**
	 * Set value of Spotify
	 * @param spotify
	 */
	public final void setSpotify(String spotify)
	{
		setSpotify(getContext(), spotify);
	}

	/**
	 * Set value of Spotify
	 * @param context
	 * @param spotify
	 */
	public final void setSpotify(com.mendix.systemwideinterfaces.core.IContext context, String spotify)
	{
		getMendixObject().setValue(context, MemberNames.Spotify.toString(), spotify);
	}

	/**
	 * @return value of External_urls_JsonObject
	 */
	public final spotify.proxies.JsonObject getExternal_urls_JsonObject() throws com.mendix.core.CoreException
	{
		return getExternal_urls_JsonObject(getContext());
	}

	/**
	 * @param context
	 * @return value of External_urls_JsonObject
	 */
	public final spotify.proxies.JsonObject getExternal_urls_JsonObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		spotify.proxies.JsonObject result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.External_urls_JsonObject.toString());
		if (identifier != null)
			result = spotify.proxies.JsonObject.load(context, identifier);
		return result;
	}

	/**
	 * Set value of External_urls_JsonObject
	 * @param external_urls_jsonobject
	 */
	public final void setExternal_urls_JsonObject(spotify.proxies.JsonObject external_urls_jsonobject)
	{
		setExternal_urls_JsonObject(getContext(), external_urls_jsonobject);
	}

	/**
	 * Set value of External_urls_JsonObject
	 * @param context
	 * @param external_urls_jsonobject
	 */
	public final void setExternal_urls_JsonObject(com.mendix.systemwideinterfaces.core.IContext context, spotify.proxies.JsonObject external_urls_jsonobject)
	{
		if (external_urls_jsonobject == null)
			getMendixObject().setValue(context, MemberNames.External_urls_JsonObject.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.External_urls_JsonObject.toString(), external_urls_jsonobject.getMendixObject().getId());
	}

	/**
	 * @return value of External_urls_Album
	 */
	public final spotify.proxies.Album getExternal_urls_Album() throws com.mendix.core.CoreException
	{
		return getExternal_urls_Album(getContext());
	}

	/**
	 * @param context
	 * @return value of External_urls_Album
	 */
	public final spotify.proxies.Album getExternal_urls_Album(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		spotify.proxies.Album result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.External_urls_Album.toString());
		if (identifier != null)
			result = spotify.proxies.Album.load(context, identifier);
		return result;
	}

	/**
	 * Set value of External_urls_Album
	 * @param external_urls_album
	 */
	public final void setExternal_urls_Album(spotify.proxies.Album external_urls_album)
	{
		setExternal_urls_Album(getContext(), external_urls_album);
	}

	/**
	 * Set value of External_urls_Album
	 * @param context
	 * @param external_urls_album
	 */
	public final void setExternal_urls_Album(com.mendix.systemwideinterfaces.core.IContext context, spotify.proxies.Album external_urls_album)
	{
		if (external_urls_album == null)
			getMendixObject().setValue(context, MemberNames.External_urls_Album.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.External_urls_Album.toString(), external_urls_album.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return external_urlsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final spotify.proxies.External_urls that = (spotify.proxies.External_urls) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Spotify.External_urls";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
