// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package spotify.proxies;

public class Images
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject imagesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Spotify.Images";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Images_JsonObject("Spotify.Images_JsonObject"),
		Images_Album("Spotify.Images_Album");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Images(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Spotify.Images"));
	}

	protected Images(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject imagesMendixObject)
	{
		if (imagesMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Spotify.Images", imagesMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Spotify.Images");

		this.imagesMendixObject = imagesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Images.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static spotify.proxies.Images initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return spotify.proxies.Images.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static spotify.proxies.Images initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new spotify.proxies.Images(context, mendixObject);
	}

	public static spotify.proxies.Images load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return spotify.proxies.Images.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Images_JsonObject
	 */
	public final spotify.proxies.JsonObject getImages_JsonObject() throws com.mendix.core.CoreException
	{
		return getImages_JsonObject(getContext());
	}

	/**
	 * @param context
	 * @return value of Images_JsonObject
	 */
	public final spotify.proxies.JsonObject getImages_JsonObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		spotify.proxies.JsonObject result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Images_JsonObject.toString());
		if (identifier != null)
			result = spotify.proxies.JsonObject.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Images_JsonObject
	 * @param images_jsonobject
	 */
	public final void setImages_JsonObject(spotify.proxies.JsonObject images_jsonobject)
	{
		setImages_JsonObject(getContext(), images_jsonobject);
	}

	/**
	 * Set value of Images_JsonObject
	 * @param context
	 * @param images_jsonobject
	 */
	public final void setImages_JsonObject(com.mendix.systemwideinterfaces.core.IContext context, spotify.proxies.JsonObject images_jsonobject)
	{
		if (images_jsonobject == null)
			getMendixObject().setValue(context, MemberNames.Images_JsonObject.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Images_JsonObject.toString(), images_jsonobject.getMendixObject().getId());
	}

	/**
	 * @return value of Images_Album
	 */
	public final spotify.proxies.Album getImages_Album() throws com.mendix.core.CoreException
	{
		return getImages_Album(getContext());
	}

	/**
	 * @param context
	 * @return value of Images_Album
	 */
	public final spotify.proxies.Album getImages_Album(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		spotify.proxies.Album result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Images_Album.toString());
		if (identifier != null)
			result = spotify.proxies.Album.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Images_Album
	 * @param images_album
	 */
	public final void setImages_Album(spotify.proxies.Album images_album)
	{
		setImages_Album(getContext(), images_album);
	}

	/**
	 * Set value of Images_Album
	 * @param context
	 * @param images_album
	 */
	public final void setImages_Album(com.mendix.systemwideinterfaces.core.IContext context, spotify.proxies.Album images_album)
	{
		if (images_album == null)
			getMendixObject().setValue(context, MemberNames.Images_Album.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Images_Album.toString(), images_album.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return imagesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final spotify.proxies.Images that = (spotify.proxies.Images) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Spotify.Images";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
