// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package spotify.proxies;

public class Items
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject itemsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Spotify.Items";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Items_Artists("Spotify.Items_Artists"),
		Items_Albums("Spotify.Items_Albums"),
		Items_Playlists("Spotify.Items_Playlists");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Items(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Spotify.Items"));
	}

	protected Items(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject itemsMendixObject)
	{
		if (itemsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Spotify.Items", itemsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Spotify.Items");

		this.itemsMendixObject = itemsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Items.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static spotify.proxies.Items initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return spotify.proxies.Items.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static spotify.proxies.Items initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new spotify.proxies.Items(context, mendixObject);
	}

	public static spotify.proxies.Items load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return spotify.proxies.Items.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Items_Artists
	 */
	public final spotify.proxies.Artists getItems_Artists() throws com.mendix.core.CoreException
	{
		return getItems_Artists(getContext());
	}

	/**
	 * @param context
	 * @return value of Items_Artists
	 */
	public final spotify.proxies.Artists getItems_Artists(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		spotify.proxies.Artists result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Items_Artists.toString());
		if (identifier != null)
			result = spotify.proxies.Artists.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Items_Artists
	 * @param items_artists
	 */
	public final void setItems_Artists(spotify.proxies.Artists items_artists)
	{
		setItems_Artists(getContext(), items_artists);
	}

	/**
	 * Set value of Items_Artists
	 * @param context
	 * @param items_artists
	 */
	public final void setItems_Artists(com.mendix.systemwideinterfaces.core.IContext context, spotify.proxies.Artists items_artists)
	{
		if (items_artists == null)
			getMendixObject().setValue(context, MemberNames.Items_Artists.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Items_Artists.toString(), items_artists.getMendixObject().getId());
	}

	/**
	 * @return value of Items_Albums
	 */
	public final spotify.proxies.Albums getItems_Albums() throws com.mendix.core.CoreException
	{
		return getItems_Albums(getContext());
	}

	/**
	 * @param context
	 * @return value of Items_Albums
	 */
	public final spotify.proxies.Albums getItems_Albums(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		spotify.proxies.Albums result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Items_Albums.toString());
		if (identifier != null)
			result = spotify.proxies.Albums.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Items_Albums
	 * @param items_albums
	 */
	public final void setItems_Albums(spotify.proxies.Albums items_albums)
	{
		setItems_Albums(getContext(), items_albums);
	}

	/**
	 * Set value of Items_Albums
	 * @param context
	 * @param items_albums
	 */
	public final void setItems_Albums(com.mendix.systemwideinterfaces.core.IContext context, spotify.proxies.Albums items_albums)
	{
		if (items_albums == null)
			getMendixObject().setValue(context, MemberNames.Items_Albums.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Items_Albums.toString(), items_albums.getMendixObject().getId());
	}

	/**
	 * @return value of Items_Playlists
	 */
	public final spotify.proxies.Playlists getItems_Playlists() throws com.mendix.core.CoreException
	{
		return getItems_Playlists(getContext());
	}

	/**
	 * @param context
	 * @return value of Items_Playlists
	 */
	public final spotify.proxies.Playlists getItems_Playlists(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		spotify.proxies.Playlists result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Items_Playlists.toString());
		if (identifier != null)
			result = spotify.proxies.Playlists.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Items_Playlists
	 * @param items_playlists
	 */
	public final void setItems_Playlists(spotify.proxies.Playlists items_playlists)
	{
		setItems_Playlists(getContext(), items_playlists);
	}

	/**
	 * Set value of Items_Playlists
	 * @param context
	 * @param items_playlists
	 */
	public final void setItems_Playlists(com.mendix.systemwideinterfaces.core.IContext context, spotify.proxies.Playlists items_playlists)
	{
		if (items_playlists == null)
			getMendixObject().setValue(context, MemberNames.Items_Playlists.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Items_Playlists.toString(), items_playlists.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return itemsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final spotify.proxies.Items that = (spotify.proxies.Items) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Spotify.Items";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
