// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package spotify.proxies;

public class JsonObject_2
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject jsonObject_2MendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Spotify.JsonObject_2";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Height("Height"),
		Url("Url"),
		Width("Width"),
		Href("Href"),
		_id("_id"),
		Name("Name"),
		_type("_type"),
		Uri("Uri"),
		JsonObject_2_Images("Spotify.JsonObject_2_Images"),
		JsonObject_2_Artists("Spotify.JsonObject_2_Artists"),
		External_urls_2_JsonObject_2("Spotify.External_urls_2_JsonObject_2");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public JsonObject_2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Spotify.JsonObject_2"));
	}

	protected JsonObject_2(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject jsonObject_2MendixObject)
	{
		if (jsonObject_2MendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Spotify.JsonObject_2", jsonObject_2MendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Spotify.JsonObject_2");

		this.jsonObject_2MendixObject = jsonObject_2MendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'JsonObject_2.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static spotify.proxies.JsonObject_2 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return spotify.proxies.JsonObject_2.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static spotify.proxies.JsonObject_2 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new spotify.proxies.JsonObject_2(context, mendixObject);
	}

	public static spotify.proxies.JsonObject_2 load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return spotify.proxies.JsonObject_2.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Height
	 */
	public final Integer getHeight()
	{
		return getHeight(getContext());
	}

	/**
	 * @param context
	 * @return value of Height
	 */
	public final Integer getHeight(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.Height.toString());
	}

	/**
	 * Set value of Height
	 * @param height
	 */
	public final void setHeight(Integer height)
	{
		setHeight(getContext(), height);
	}

	/**
	 * Set value of Height
	 * @param context
	 * @param height
	 */
	public final void setHeight(com.mendix.systemwideinterfaces.core.IContext context, Integer height)
	{
		getMendixObject().setValue(context, MemberNames.Height.toString(), height);
	}

	/**
	 * @return value of Url
	 */
	public final String getUrl()
	{
		return getUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of Url
	 */
	public final String getUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Url.toString());
	}

	/**
	 * Set value of Url
	 * @param url
	 */
	public final void setUrl(String url)
	{
		setUrl(getContext(), url);
	}

	/**
	 * Set value of Url
	 * @param context
	 * @param url
	 */
	public final void setUrl(com.mendix.systemwideinterfaces.core.IContext context, String url)
	{
		getMendixObject().setValue(context, MemberNames.Url.toString(), url);
	}

	/**
	 * @return value of Width
	 */
	public final Integer getWidth()
	{
		return getWidth(getContext());
	}

	/**
	 * @param context
	 * @return value of Width
	 */
	public final Integer getWidth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.Width.toString());
	}

	/**
	 * Set value of Width
	 * @param width
	 */
	public final void setWidth(Integer width)
	{
		setWidth(getContext(), width);
	}

	/**
	 * Set value of Width
	 * @param context
	 * @param width
	 */
	public final void setWidth(com.mendix.systemwideinterfaces.core.IContext context, Integer width)
	{
		getMendixObject().setValue(context, MemberNames.Width.toString(), width);
	}

	/**
	 * @return value of Href
	 */
	public final String getHref()
	{
		return getHref(getContext());
	}

	/**
	 * @param context
	 * @return value of Href
	 */
	public final String getHref(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Href.toString());
	}

	/**
	 * Set value of Href
	 * @param href
	 */
	public final void setHref(String href)
	{
		setHref(getContext(), href);
	}

	/**
	 * Set value of Href
	 * @param context
	 * @param href
	 */
	public final void setHref(com.mendix.systemwideinterfaces.core.IContext context, String href)
	{
		getMendixObject().setValue(context, MemberNames.Href.toString(), href);
	}

	/**
	 * @return value of _id
	 */
	public final String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of Name
	 */
	public final String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of _type
	 */
	public final String get_type()
	{
		return get_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _type
	 */
	public final String get_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames._type.toString());
	}

	/**
	 * Set value of _type
	 * @param _type
	 */
	public final void set_type(String _type)
	{
		set_type(getContext(), _type);
	}

	/**
	 * Set value of _type
	 * @param context
	 * @param _type
	 */
	public final void set_type(com.mendix.systemwideinterfaces.core.IContext context, String _type)
	{
		getMendixObject().setValue(context, MemberNames._type.toString(), _type);
	}

	/**
	 * @return value of Uri
	 */
	public final String getUri()
	{
		return getUri(getContext());
	}

	/**
	 * @param context
	 * @return value of Uri
	 */
	public final String getUri(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Uri.toString());
	}

	/**
	 * Set value of Uri
	 * @param uri
	 */
	public final void setUri(String uri)
	{
		setUri(getContext(), uri);
	}

	/**
	 * Set value of Uri
	 * @param context
	 * @param uri
	 */
	public final void setUri(com.mendix.systemwideinterfaces.core.IContext context, String uri)
	{
		getMendixObject().setValue(context, MemberNames.Uri.toString(), uri);
	}

	/**
	 * @return value of JsonObject_2_Images
	 */
	public final spotify.proxies.Images getJsonObject_2_Images() throws com.mendix.core.CoreException
	{
		return getJsonObject_2_Images(getContext());
	}

	/**
	 * @param context
	 * @return value of JsonObject_2_Images
	 */
	public final spotify.proxies.Images getJsonObject_2_Images(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		spotify.proxies.Images result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.JsonObject_2_Images.toString());
		if (identifier != null)
			result = spotify.proxies.Images.load(context, identifier);
		return result;
	}

	/**
	 * Set value of JsonObject_2_Images
	 * @param jsonobject_2_images
	 */
	public final void setJsonObject_2_Images(spotify.proxies.Images jsonobject_2_images)
	{
		setJsonObject_2_Images(getContext(), jsonobject_2_images);
	}

	/**
	 * Set value of JsonObject_2_Images
	 * @param context
	 * @param jsonobject_2_images
	 */
	public final void setJsonObject_2_Images(com.mendix.systemwideinterfaces.core.IContext context, spotify.proxies.Images jsonobject_2_images)
	{
		if (jsonobject_2_images == null)
			getMendixObject().setValue(context, MemberNames.JsonObject_2_Images.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.JsonObject_2_Images.toString(), jsonobject_2_images.getMendixObject().getId());
	}

	/**
	 * @return value of JsonObject_2_Artists
	 */
	public final spotify.proxies.Artists getJsonObject_2_Artists() throws com.mendix.core.CoreException
	{
		return getJsonObject_2_Artists(getContext());
	}

	/**
	 * @param context
	 * @return value of JsonObject_2_Artists
	 */
	public final spotify.proxies.Artists getJsonObject_2_Artists(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		spotify.proxies.Artists result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.JsonObject_2_Artists.toString());
		if (identifier != null)
			result = spotify.proxies.Artists.load(context, identifier);
		return result;
	}

	/**
	 * Set value of JsonObject_2_Artists
	 * @param jsonobject_2_artists
	 */
	public final void setJsonObject_2_Artists(spotify.proxies.Artists jsonobject_2_artists)
	{
		setJsonObject_2_Artists(getContext(), jsonobject_2_artists);
	}

	/**
	 * Set value of JsonObject_2_Artists
	 * @param context
	 * @param jsonobject_2_artists
	 */
	public final void setJsonObject_2_Artists(com.mendix.systemwideinterfaces.core.IContext context, spotify.proxies.Artists jsonobject_2_artists)
	{
		if (jsonobject_2_artists == null)
			getMendixObject().setValue(context, MemberNames.JsonObject_2_Artists.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.JsonObject_2_Artists.toString(), jsonobject_2_artists.getMendixObject().getId());
	}

	/**
	 * @return value of External_urls_2_JsonObject_2
	 */
	public final spotify.proxies.External_urls_2 getExternal_urls_2_JsonObject_2() throws com.mendix.core.CoreException
	{
		return getExternal_urls_2_JsonObject_2(getContext());
	}

	/**
	 * @param context
	 * @return value of External_urls_2_JsonObject_2
	 */
	public final spotify.proxies.External_urls_2 getExternal_urls_2_JsonObject_2(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		spotify.proxies.External_urls_2 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.External_urls_2_JsonObject_2.toString());
		if (identifier != null)
			result = spotify.proxies.External_urls_2.load(context, identifier);
		return result;
	}

	/**
	 * Set value of External_urls_2_JsonObject_2
	 * @param external_urls_2_jsonobject_2
	 */
	public final void setExternal_urls_2_JsonObject_2(spotify.proxies.External_urls_2 external_urls_2_jsonobject_2)
	{
		setExternal_urls_2_JsonObject_2(getContext(), external_urls_2_jsonobject_2);
	}

	/**
	 * Set value of External_urls_2_JsonObject_2
	 * @param context
	 * @param external_urls_2_jsonobject_2
	 */
	public final void setExternal_urls_2_JsonObject_2(com.mendix.systemwideinterfaces.core.IContext context, spotify.proxies.External_urls_2 external_urls_2_jsonobject_2)
	{
		if (external_urls_2_jsonobject_2 == null)
			getMendixObject().setValue(context, MemberNames.External_urls_2_JsonObject_2.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.External_urls_2_JsonObject_2.toString(), external_urls_2_jsonobject_2.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return jsonObject_2MendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final spotify.proxies.JsonObject_2 that = (spotify.proxies.JsonObject_2) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Spotify.JsonObject_2";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
